apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: 'Multiple model serving and RAG demonstration components'
    openshift.io/display-name: demo-modelmesh
  labels:
    opendatahub.io/dashboard: 'true'
  name: demo-modelmesh
spec: {}