apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: 'Single model serving and RAG demonstration components'
    openshift.io/display-name: demo-kserve
  labels:
    opendatahub.io/dashboard: 'true'
  name: demo-kserve
spec: {}