apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: model-serving-demo
  labels:
    app: minio
    chart: minio-5.2.0
    release: minio
    heritage: Helm
type: Opaque
data:
  MINIO_ROOT_USER: "cm9vdHVzZXI="
  MINIO_ROOT_PASSWORD: "cm9vdHVzZXIxMjM="