apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nvidia-gpu-operator-ns.yaml
- nvidia-gpu-operator-group.yaml
- nvidia-gpu-operator-subscription.yaml
- nvidia-gpu-clusterpolicy.yaml
