
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: job-generic
    namespace: nvidia-gpu-operator
    files:
      - job.sh
      - ocp.sh
