apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - model-serving-demo-ns.yaml
  - minio-secret.yaml
  - service-account.yaml
  - pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - minio-routes.yaml
  - setup-minio-job.yaml

configMapGenerator:
  - name: minio-config
    namespace: model-serving-demo
    files:
      - minio-tools.py
      - job.sh