---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-setup-account
  namespace: model-serving-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-setup-cluster-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-setup-reader
roleRef:
  kind: ClusterRole
  name: demo-setup-cluster-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: demo-setup-account
    namespace: model-serving-demo