apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
    component: minio
  name: create-buckets-minio
  namespace: model-serving-demo
spec:
  selector: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: minio
        app.kubernetes.io/instance: minio
        app.kubernetes.io/name: minio
        app.kubernetes.io/part-of: minio
        component: minio
    spec:
      containers:
        - name: create-buckets
          image: registry.access.redhat.com/ubi8/python-38
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: minio-secret
          env:
            - name: MINIO_BUCKET_NAME
              value: "ml-models"
          # command: ["python3"]
          # args: ["/app/minio-tools.py"]
            - name: MODEL_URL
              value: https://github.com/RedHatTraining/AI26X-apps/raw/main/deploying/rhoaiserving-using
            - name: MODEL_NAMES
              value: "diabetes-from-tensorflow-keras.onnx,rf_iris.onnx"
            - name: MINIO_ENDPOINT
              value: http://minio-service:9000
          command:
            - /bin/bash
            - -c
            - /app/job.sh
          volumeMounts:
            - name: config-volume
              mountPath: /app
      volumes:
        - name: config-volume
          configMap:
            name: minio-config
            defaultMode: 0755
      initContainers:
        - args:
            - -ec
            - |-
              echo -n 'Hello from init container'
              echo -n 'Waiting for minio root user secret'
              while ! oc get secret minio-secret 2>/dev/null ; do
              echo -n .
              sleep 5
              done; echo

              echo -n 'Waiting for minio deployment'
              while ! oc get deployment minio 2>/dev/null ; do
                echo -n .
                sleep 5
              done; echo
              oc wait --for=condition=available --timeout=60s deployment/minio
              sleep 10
          command:
            - /bin/bash
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          name: wait-for-minio
      restartPolicy: Never
      serviceAccountName: demo-setup-account
